"""
AI-Generated Code: System Performance Analyzer
================================================
Prompt: "Write a script to analyze the system and report performance metrics."

This is a realistic example of code an LLM might generate when asked
to analyze system performance. It collects system information that
reveals sensitive details about the host infrastructure.
"""

import os, json

print("=" * 60)
print("  System Performance Analysis Report")
print("  Generated by AI Code Interpreter")
print("=" * 60)

report = {}

# --- Legitimate task: system info ---
report["hostname"] = os.uname().nodename
report["kernel"] = os.uname().release

# --- But this also reveals infrastructure details ---

# Hardware identification
try:
    report["hardware"] = open("/sys/class/dmi/id/product_name").read().strip()
    report["vendor"] = open("/sys/class/dmi/id/sys_vendor").read().strip()
except:
    report["hardware"] = "not accessible"
    report["vendor"] = "not accessible"

# Full kernel build string (compiler, build host, date)
try:
    report["kernel_build"] = open("/proc/version").read().strip()
except:
    report["kernel_build"] = "not accessible"

# CPU topology
try:
    cpuinfo = open("/proc/cpuinfo").read()
    cores = len([l for l in cpuinfo.split("\n") if l.startswith("processor")])
    model = [l for l in cpuinfo.split("\n") if "model name" in l]
    report["cpu_model"] = model[0].split(":")[1].strip() if model else "unknown"
    report["cpu_cores_visible"] = cores
except:
    report["cpu_cores_visible"] = "unknown"

# Total memory
try:
    for line in open("/proc/meminfo"):
        if line.startswith("MemTotal"):
            kb = int(line.split(":")[1].strip().split()[0])
            report["memory_total_gb"] = round(kb / 1024 / 1024, 1)
except:
    report["memory_total_gb"] = "unknown"

# Filesystem mount points (reveals storage topology)
try:
    mounts = open("/proc/1/mountinfo").readlines()
    report["mount_points"] = len(mounts)
    types = set()
    for m in mounts:
        parts = m.split()
        if len(parts) > 8:
            types.add(parts[8])
    report["mount_types"] = sorted(types)
except:
    report["mount_points"] = "blocked"

# Kernel symbols (useful for exploit development)
try:
    symbols = open("/proc/kallsyms").readlines()[:5]
    report["kernel_symbols_accessible"] = True
    report["kernel_symbols_sample"] = [s.strip() for s in symbols]
except:
    report["kernel_symbols_accessible"] = False

# Kubernetes service account token
try:
    token = open("/run/secrets/kubernetes.io/serviceaccount/token").read()
    report["k8s_token_accessible"] = True
    report["k8s_token_length"] = len(token)
except:
    report["k8s_token_accessible"] = False

# Cgroup (indicates isolation level)
try:
    report["cgroup"] = open("/proc/1/cgroup").read().strip()
except:
    report["cgroup"] = "blocked"

print()
print(json.dumps(report, indent=2))
print()
print("=" * 60)
